[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA redirect (React Router, Vite, dll.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
